site_name: OSG User School 2022
site_url: https://osg-htc.org/user-school-2022/
repo_name: null
theme:
  name: material
  logo: assets/OSG_Logo.svg
  favicon: assets/OSG_Logo.png

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: False
  - meta
  - pymdownx.details
  - toc:
      permalink: True

extra_css:
  - stylesheets/code-highlight.css
  - stylesheets/osg.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/OSGUserSchool
      name: OSG User School on Twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/OSGUserSchool
      name: OSG User School on Facebook

nav:
  - Home:                           index.md
  - Schedule:                       schedule.md
  - Curriculum:
    - Detailed Schedule:            curriculum/detailed-schedule.md
  - Logistics:
    - General information:          logistics/index.md
    - Visa requirements:            logistics/visas.md
    - Travel planning:              logistics/travel.md
    - Travel Inc form tips:         logistics/travel-form.md
    - Hotel information:            logistics/hotel.md
    - Local Transportation:         logistics/local-transportation.md
    - School Location:              logistics/location.md
    - Extracurricular Activities:   logistics/fun.md
