site_name: OSG User School 2022
site_url: https://osg-htc.org/user-school-2022/
repo_name: null
theme:
  name: material
  logo: assets/OSG_Logo.svg
  favicon: assets/OSG_Logo.png

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: False
  - meta
  - pymdownx.details
  - toc:
      permalink: True

extra_css:
  - stylesheets/code-highlight.css
  - stylesheets/osg.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/OSGUserSchool
      name: OSG User School on Twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/OSGUserSchool
      name: OSG User School on Facebook

nav:
  - Home:                           index.md
  - Schedule:                       schedule.md
  - COVID policy:                   covid-policy.md
  - Logistics:
    - General information:          logistics/index.md
    - Travel:
      - Advice:                     logistics/travel-advice.md
      - Local transportation:       logistics/local-transportation.md
      - Travel planning:            logistics/travel.md
      - Travel Inc form tips:       logistics/travel-form.md
    - Visa requirements:            logistics/visas.md
    - Hotel information:            logistics/hotel.md
    - School location:              logistics/location.md
    - Meals at the School:          logistics/meals.md
    - Fun activities:               logistics/fun.md
  - Materials:
    - Overview:                     materials/index.md
    - HTC Exercises:
      - Exercise 1.1:               materials/htcondor/part1-ex1-login.md
      - Exercise 1.2:               materials/htcondor/part1-ex2-commands.md
      - Exercise 1.3:               materials/htcondor/part1-ex3-jobs.md
      - Exercise 1.4:               materials/htcondor/part1-ex4-logs.md
      - Exercise 1.5:               materials/htcondor/part1-ex5-request.md
      - Exercise 1.6:               materials/htcondor/part1-ex6-remove.md
      - Bonus Exercise 1.7:         materials/htcondor/part1-ex7-compile.md
      - Bonus Exercise 1.8:         materials/htcondor/part1-ex8-queue.md
      - Bonus Exercise 1.9:         materials/htcondor/part1-ex9-status.md
      - Bonus Exercise 1.10:        materials/htcondor/part1-ex10-job-retry.md
      - Exercise 2.1:               materials/htcondor/part2-ex1-files.md
      - Exercise 2.2:               materials/htcondor/part2-ex2-queue-n.md
      - Exercise 2.3:               materials/htcondor/part2-ex3-queue-from.md
      - Exercise 2.4:               materials/htcondor/part2-ex4-queue-matching.md 
    - Software Exercises:
      - Exercise 1.1:               materials/software/part1-ex1-download.md
      - Exercise 1.2:               materials/software/part1-ex2-wrapper.md
      - Exercise 1.3:               materials/software/part1-ex3-arguments.md
      - Exercise 2.1:               materials/software/part2-ex1-compiling.md
      - Exercise 2.2:               materials/software/part2-ex2-prepackaged.md
      - Exercise 2.3:               materials/software/part2-ex3-python.md
      - Exercise 2.4:               materials/software/part2-ex4-matlab.md
      - Exercise 2.5:               materials/software/part2-ex5-conda.md
      - Exercise 3.1:               materials/software/part3-ex1-singularity.md
      - Exercise 3.2:               materials/software/part3-ex2-singularity-options.md
      - Exercise 4.1:               materials/software/part4-ex1-docker.md
      - Exercise 4.2:               materials/software/part4-ex2-docker-build.md
    - Data Exercises:
      - Exercise 1.1:               materials/data/part1-ex1-data-needs.md
      - Exercise 1.2:               materials/data/part1-ex2-file-transfer.md
      - Exercise 1.3:               materials/data/part1-ex3-blast-split.md
      - Exercise 2.1:               materials/data/part2-ex1-blast-proxy.md
      - Exercise 2.2:               materials/data/part2-ex2-stash-shared.md
      - Exercise 2.3:               materials/data/part2-ex3-stash-unique.md
      - Bonus Exercise 3.1:         materials/data/part3-ex1-input.md
      - Bonus Exercise 3.2:         materials/data/part3-ex2-output.md
    - Checkpointing Exercises:
      - Exercise 1.1:               materials/checkpoint/part1-ex1-checkpointing.md
